using System.Text.Json;
using GearBox.Core.Model.Json;
using GearBox.Core.Model.Units;

namespace GearBox.Core.Model.Dynamic;

/// <summary>
/// Projectiles are generated by characters when they use attacks, and can inflict damage
/// </summary>
public class Projectile : IDynamicGameObject
{
    private readonly MobileBehavior _mobility;
    private readonly Distance _range;
    private double _distanceTraveledInPixels = 0;
    private bool _hasCollided; // this will have to wait until after Teams

    public Projectile(Coordinates coordinates, Velocity velocity, Distance range, Attack attack)
    {
        Body = new()
        {
            Location = coordinates
        };
        Body.Collided += attack.HandleCollision;
        _mobility = new(Body, velocity);
        _mobility.StartMovingIn(velocity.Angle); // MobileBehavior defaults to not moving
        _range = range;
    }

    public string Type => "projectile";
    public BodyBehavior Body { get; init; }
    public bool IsTerminated => _hasCollided || _range.InPixels <= _distanceTraveledInPixels;

    public void Update()
    {
        _mobility.UpdateMovement();
        _distanceTraveledInPixels += _mobility.Velocity.Magnitude.InPixelsPerFrame;
    }

    public string Serialize(JsonSerializerOptions options)
    {
        var json = new ProjectileJson(
            Body.Location.XInPixels, 
            Body.Location.YInPixels
        );
        return JsonSerializer.Serialize(json, options);
    }
}