using GearBox.Core.Model.Json;
using GearBox.Core.Model.Units;

namespace GearBox.Core.Model.Dynamic;

/// <summary>
/// Projectiles are generated by characters when they use attacks, and can inflict damage
/// </summary>
public class Projectile : IDynamicGameObject
{
    private readonly MobileBehavior _mobility;
    private readonly Distance _range;
    private double _distanceTraveledInPixels = 0;
    private bool _hasCollided;

    public Projectile(Coordinates coordinates, Velocity velocity, Distance range)
    {
        Body = new()
        {
            Location = coordinates
        };
        _mobility = new(Body, velocity);
        _mobility.StartMovingIn(velocity.Angle); // MobileBehavior defaults to not moving
        _range = range;
    }

    public BodyBehavior Body { get; init; }
    public bool IsTerminated => _hasCollided || _range.InPixels <= _distanceTraveledInPixels;

    // todo add a player collider thing

    public IDynamicGameObjectJson ToJson()
    {
        var result = new ProjectileJson(
            Body.Location.XInPixels, 
            Body.Location.YInPixels
        );
        return result;
    }

    public void Update()
    {
        _mobility.UpdateMovement();
        _distanceTraveledInPixels += _mobility.Velocity.Magnitude.InPixelsPerFrame;
    }
}